FROM python:3.8

WORKDIR .

COPY ./cusip_generator_api /cusip_generator_api
COPY ./app.py /app.py
COPY ./requirements.txt /requirements.txt

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

ENTRYPOINT [ "python" ]

CMD [ "app.py" ]