FROM node:13.12.0-alpine

WORKDIR .

COPY ./src /src
COPY ./package-lock.json /package-lock.json
COPY ./package.json /package.json
COPY ./public /public

RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent

CMD [ "npm", "start" ]